export const FACE_DETECTION_CONFIG = {
  THROTTLE_MS: 400,
  EYE_CLOSED_THRESHOLD: 0.2,
  YAW_BACK_THRESHOLD: 20,
  YAW_GO_THRESHOLD: -20,
  PITCH_UP_THRESHOLD: 15,
  PITCH_DOWN_THRESHOLD: -9,
} as const;

export const CAMERA_CONFIG = {
  PERFORMANCE_MODE: 'fast',
  CLASSIFICATION_MODE: 'all',
  CONTOUR_MODE: 'none',
  LANDMARK_MODE: 'none',
} as const;
